# Étape 1 : Construction de l'application Angular
FROM node:16 AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Mettre à jour npm et installer les dépendances avec un délai d'attente plus long
RUN npm install -g npm@10.9.0
RUN npm install --legacy-peer-deps --fetch-timeout=60000 --network-timeout=60000

# Copier tous les fichiers sources de l'application
COPY . .

# Construire l'application Angular pour la production
RUN npm run build --prod
