# Étape 1 : Construction de l'application Angular
FROM node:18 AS build  # Utilisation de Node.js version 18 LTS, compatible avec Angular

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Mettre à jour npm à une version compatible
RUN npm install -g npm@10.9.0

# Installer les dépendances avec un délai d'attente plus long
RUN npm install --legacy-peer-deps --fetch-timeout=60000 --network-timeout=60000

# Copier tous les fichiers sources de l'application
COPY . .

# Construire l'application Angular pour la production
RUN npm run build --prod

# Étape 2 : Serveur Nginx pour l'application construite
FROM nginx:alpine

# Copier les fichiers construits depuis l'étape précédente vers le dossier par défaut de Nginx
COPY --from=build /app/dist/nom-du-projet-angular /usr/share/nginx/html

# Exposer le port 80 pour accéder à l'application
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
