version: '3.8'

services:
  # Service pour la base de données MySQL
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: samar123*/
      MYSQL_DATABASE: databaseBank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Service pour le backend Spring Boot
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure
    container_name: backend_service
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysql_db:3306/databaseBank?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "samar123*/",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }

  # Service pour le frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: on-failure
    container_name: frontend_service
    ports:
      - "4200:80"  # Mappe le port 4200 de l'hôte au port 80 du conteneur Nginx pour Angular

  # Service pour Nexus
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      NEXUS_CONTEXT: /

  # Service pour SonarQube
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  # Service pour Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8084:8080"      # Port pour l'interface Jenkins
      - "50000:50000"    # Port pour les agents Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # Désactive l'assistant d'installation initial si vous avez un fichier de config JCasC

volumes:
  mysql_data:
  nexus_data:
  jenkins_data:
